//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace SSS_WEB_APPLICATION.SSS_WEB_SERVICE {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SSS_SERVICESoap", Namespace="http://tempuri.org/")]
    public partial class SSS_SERVICE : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback INSERT_IMAGEOperationCompleted;
        
        private System.Threading.SendOrPostCallback INSERT_USEROperationCompleted;
        
        private System.Threading.SendOrPostCallback UPDATE_TRAIN_DATAOperationCompleted;
        
        private System.Threading.SendOrPostCallback TRAIN_IMAGES_MODELOperationCompleted;
        
        private System.Threading.SendOrPostCallback RETURN_TRAINED_MODELSOperationCompleted;
        
        private System.Threading.SendOrPostCallback RETURN_USERS_IN_MODELOperationCompleted;
        
        private System.Threading.SendOrPostCallback RETURN_USER_WITH_IDOperationCompleted;
        
        private System.Threading.SendOrPostCallback DECREMENT_IMAGES_MODEL_VERSIONOperationCompleted;
        
        private System.Threading.SendOrPostCallback return_UsersOperationCompleted;
        
        private System.Threading.SendOrPostCallback return_ImagesOperationCompleted;
        
        private System.Threading.SendOrPostCallback CONTACT_JAVA_SERVEROperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public SSS_SERVICE() {
            this.Url = global::SSS_WEB_APPLICATION.Properties.Settings.Default.SSS_WEB_APPLICATION_SSS_WEB_SERVICE_SSS_SERVICE;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event INSERT_IMAGECompletedEventHandler INSERT_IMAGECompleted;
        
        /// <remarks/>
        public event INSERT_USERCompletedEventHandler INSERT_USERCompleted;
        
        /// <remarks/>
        public event UPDATE_TRAIN_DATACompletedEventHandler UPDATE_TRAIN_DATACompleted;
        
        /// <remarks/>
        public event TRAIN_IMAGES_MODELCompletedEventHandler TRAIN_IMAGES_MODELCompleted;
        
        /// <remarks/>
        public event RETURN_TRAINED_MODELSCompletedEventHandler RETURN_TRAINED_MODELSCompleted;
        
        /// <remarks/>
        public event RETURN_USERS_IN_MODELCompletedEventHandler RETURN_USERS_IN_MODELCompleted;
        
        /// <remarks/>
        public event RETURN_USER_WITH_IDCompletedEventHandler RETURN_USER_WITH_IDCompleted;
        
        /// <remarks/>
        public event DECREMENT_IMAGES_MODEL_VERSIONCompletedEventHandler DECREMENT_IMAGES_MODEL_VERSIONCompleted;
        
        /// <remarks/>
        public event return_UsersCompletedEventHandler return_UsersCompleted;
        
        /// <remarks/>
        public event return_ImagesCompletedEventHandler return_ImagesCompleted;
        
        /// <remarks/>
        public event CONTACT_JAVA_SERVERCompletedEventHandler CONTACT_JAVA_SERVERCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/INSERT_IMAGE", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string INSERT_IMAGE(string user_ID, string image_Path) {
            object[] results = this.Invoke("INSERT_IMAGE", new object[] {
                        user_ID,
                        image_Path});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void INSERT_IMAGEAsync(string user_ID, string image_Path) {
            this.INSERT_IMAGEAsync(user_ID, image_Path, null);
        }
        
        /// <remarks/>
        public void INSERT_IMAGEAsync(string user_ID, string image_Path, object userState) {
            if ((this.INSERT_IMAGEOperationCompleted == null)) {
                this.INSERT_IMAGEOperationCompleted = new System.Threading.SendOrPostCallback(this.OnINSERT_IMAGEOperationCompleted);
            }
            this.InvokeAsync("INSERT_IMAGE", new object[] {
                        user_ID,
                        image_Path}, this.INSERT_IMAGEOperationCompleted, userState);
        }
        
        private void OnINSERT_IMAGEOperationCompleted(object arg) {
            if ((this.INSERT_IMAGECompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.INSERT_IMAGECompleted(this, new INSERT_IMAGECompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/INSERT_USER", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string INSERT_USER(string user_Name) {
            object[] results = this.Invoke("INSERT_USER", new object[] {
                        user_Name});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void INSERT_USERAsync(string user_Name) {
            this.INSERT_USERAsync(user_Name, null);
        }
        
        /// <remarks/>
        public void INSERT_USERAsync(string user_Name, object userState) {
            if ((this.INSERT_USEROperationCompleted == null)) {
                this.INSERT_USEROperationCompleted = new System.Threading.SendOrPostCallback(this.OnINSERT_USEROperationCompleted);
            }
            this.InvokeAsync("INSERT_USER", new object[] {
                        user_Name}, this.INSERT_USEROperationCompleted, userState);
        }
        
        private void OnINSERT_USEROperationCompleted(object arg) {
            if ((this.INSERT_USERCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.INSERT_USERCompleted(this, new INSERT_USERCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UPDATE_TRAIN_DATA", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string UPDATE_TRAIN_DATA(string user_ID) {
            object[] results = this.Invoke("UPDATE_TRAIN_DATA", new object[] {
                        user_ID});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void UPDATE_TRAIN_DATAAsync(string user_ID) {
            this.UPDATE_TRAIN_DATAAsync(user_ID, null);
        }
        
        /// <remarks/>
        public void UPDATE_TRAIN_DATAAsync(string user_ID, object userState) {
            if ((this.UPDATE_TRAIN_DATAOperationCompleted == null)) {
                this.UPDATE_TRAIN_DATAOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUPDATE_TRAIN_DATAOperationCompleted);
            }
            this.InvokeAsync("UPDATE_TRAIN_DATA", new object[] {
                        user_ID}, this.UPDATE_TRAIN_DATAOperationCompleted, userState);
        }
        
        private void OnUPDATE_TRAIN_DATAOperationCompleted(object arg) {
            if ((this.UPDATE_TRAIN_DATACompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UPDATE_TRAIN_DATACompleted(this, new UPDATE_TRAIN_DATACompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TRAIN_IMAGES_MODEL", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string TRAIN_IMAGES_MODEL(string user_ID) {
            object[] results = this.Invoke("TRAIN_IMAGES_MODEL", new object[] {
                        user_ID});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void TRAIN_IMAGES_MODELAsync(string user_ID) {
            this.TRAIN_IMAGES_MODELAsync(user_ID, null);
        }
        
        /// <remarks/>
        public void TRAIN_IMAGES_MODELAsync(string user_ID, object userState) {
            if ((this.TRAIN_IMAGES_MODELOperationCompleted == null)) {
                this.TRAIN_IMAGES_MODELOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTRAIN_IMAGES_MODELOperationCompleted);
            }
            this.InvokeAsync("TRAIN_IMAGES_MODEL", new object[] {
                        user_ID}, this.TRAIN_IMAGES_MODELOperationCompleted, userState);
        }
        
        private void OnTRAIN_IMAGES_MODELOperationCompleted(object arg) {
            if ((this.TRAIN_IMAGES_MODELCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TRAIN_IMAGES_MODELCompleted(this, new TRAIN_IMAGES_MODELCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RETURN_TRAINED_MODELS", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] RETURN_TRAINED_MODELS() {
            object[] results = this.Invoke("RETURN_TRAINED_MODELS", new object[0]);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void RETURN_TRAINED_MODELSAsync() {
            this.RETURN_TRAINED_MODELSAsync(null);
        }
        
        /// <remarks/>
        public void RETURN_TRAINED_MODELSAsync(object userState) {
            if ((this.RETURN_TRAINED_MODELSOperationCompleted == null)) {
                this.RETURN_TRAINED_MODELSOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRETURN_TRAINED_MODELSOperationCompleted);
            }
            this.InvokeAsync("RETURN_TRAINED_MODELS", new object[0], this.RETURN_TRAINED_MODELSOperationCompleted, userState);
        }
        
        private void OnRETURN_TRAINED_MODELSOperationCompleted(object arg) {
            if ((this.RETURN_TRAINED_MODELSCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RETURN_TRAINED_MODELSCompleted(this, new RETURN_TRAINED_MODELSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RETURN_USERS_IN_MODEL", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] RETURN_USERS_IN_MODEL(string Model_ID) {
            object[] results = this.Invoke("RETURN_USERS_IN_MODEL", new object[] {
                        Model_ID});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void RETURN_USERS_IN_MODELAsync(string Model_ID) {
            this.RETURN_USERS_IN_MODELAsync(Model_ID, null);
        }
        
        /// <remarks/>
        public void RETURN_USERS_IN_MODELAsync(string Model_ID, object userState) {
            if ((this.RETURN_USERS_IN_MODELOperationCompleted == null)) {
                this.RETURN_USERS_IN_MODELOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRETURN_USERS_IN_MODELOperationCompleted);
            }
            this.InvokeAsync("RETURN_USERS_IN_MODEL", new object[] {
                        Model_ID}, this.RETURN_USERS_IN_MODELOperationCompleted, userState);
        }
        
        private void OnRETURN_USERS_IN_MODELOperationCompleted(object arg) {
            if ((this.RETURN_USERS_IN_MODELCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RETURN_USERS_IN_MODELCompleted(this, new RETURN_USERS_IN_MODELCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RETURN_USER_WITH_ID", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string RETURN_USER_WITH_ID(string user_ID) {
            object[] results = this.Invoke("RETURN_USER_WITH_ID", new object[] {
                        user_ID});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void RETURN_USER_WITH_IDAsync(string user_ID) {
            this.RETURN_USER_WITH_IDAsync(user_ID, null);
        }
        
        /// <remarks/>
        public void RETURN_USER_WITH_IDAsync(string user_ID, object userState) {
            if ((this.RETURN_USER_WITH_IDOperationCompleted == null)) {
                this.RETURN_USER_WITH_IDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRETURN_USER_WITH_IDOperationCompleted);
            }
            this.InvokeAsync("RETURN_USER_WITH_ID", new object[] {
                        user_ID}, this.RETURN_USER_WITH_IDOperationCompleted, userState);
        }
        
        private void OnRETURN_USER_WITH_IDOperationCompleted(object arg) {
            if ((this.RETURN_USER_WITH_IDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RETURN_USER_WITH_IDCompleted(this, new RETURN_USER_WITH_IDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DECREMENT_IMAGES_MODEL_VERSION", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string DECREMENT_IMAGES_MODEL_VERSION(string user_ID) {
            object[] results = this.Invoke("DECREMENT_IMAGES_MODEL_VERSION", new object[] {
                        user_ID});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void DECREMENT_IMAGES_MODEL_VERSIONAsync(string user_ID) {
            this.DECREMENT_IMAGES_MODEL_VERSIONAsync(user_ID, null);
        }
        
        /// <remarks/>
        public void DECREMENT_IMAGES_MODEL_VERSIONAsync(string user_ID, object userState) {
            if ((this.DECREMENT_IMAGES_MODEL_VERSIONOperationCompleted == null)) {
                this.DECREMENT_IMAGES_MODEL_VERSIONOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDECREMENT_IMAGES_MODEL_VERSIONOperationCompleted);
            }
            this.InvokeAsync("DECREMENT_IMAGES_MODEL_VERSION", new object[] {
                        user_ID}, this.DECREMENT_IMAGES_MODEL_VERSIONOperationCompleted, userState);
        }
        
        private void OnDECREMENT_IMAGES_MODEL_VERSIONOperationCompleted(object arg) {
            if ((this.DECREMENT_IMAGES_MODEL_VERSIONCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DECREMENT_IMAGES_MODEL_VERSIONCompleted(this, new DECREMENT_IMAGES_MODEL_VERSIONCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/return_Users", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public User[] return_Users() {
            object[] results = this.Invoke("return_Users", new object[0]);
            return ((User[])(results[0]));
        }
        
        /// <remarks/>
        public void return_UsersAsync() {
            this.return_UsersAsync(null);
        }
        
        /// <remarks/>
        public void return_UsersAsync(object userState) {
            if ((this.return_UsersOperationCompleted == null)) {
                this.return_UsersOperationCompleted = new System.Threading.SendOrPostCallback(this.Onreturn_UsersOperationCompleted);
            }
            this.InvokeAsync("return_Users", new object[0], this.return_UsersOperationCompleted, userState);
        }
        
        private void Onreturn_UsersOperationCompleted(object arg) {
            if ((this.return_UsersCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.return_UsersCompleted(this, new return_UsersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/return_Images", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Image[] return_Images() {
            object[] results = this.Invoke("return_Images", new object[0]);
            return ((Image[])(results[0]));
        }
        
        /// <remarks/>
        public void return_ImagesAsync() {
            this.return_ImagesAsync(null);
        }
        
        /// <remarks/>
        public void return_ImagesAsync(object userState) {
            if ((this.return_ImagesOperationCompleted == null)) {
                this.return_ImagesOperationCompleted = new System.Threading.SendOrPostCallback(this.Onreturn_ImagesOperationCompleted);
            }
            this.InvokeAsync("return_Images", new object[0], this.return_ImagesOperationCompleted, userState);
        }
        
        private void Onreturn_ImagesOperationCompleted(object arg) {
            if ((this.return_ImagesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.return_ImagesCompleted(this, new return_ImagesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CONTACT_JAVA_SERVER", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string CONTACT_JAVA_SERVER() {
            object[] results = this.Invoke("CONTACT_JAVA_SERVER", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CONTACT_JAVA_SERVERAsync() {
            this.CONTACT_JAVA_SERVERAsync(null);
        }
        
        /// <remarks/>
        public void CONTACT_JAVA_SERVERAsync(object userState) {
            if ((this.CONTACT_JAVA_SERVEROperationCompleted == null)) {
                this.CONTACT_JAVA_SERVEROperationCompleted = new System.Threading.SendOrPostCallback(this.OnCONTACT_JAVA_SERVEROperationCompleted);
            }
            this.InvokeAsync("CONTACT_JAVA_SERVER", new object[0], this.CONTACT_JAVA_SERVEROperationCompleted, userState);
        }
        
        private void OnCONTACT_JAVA_SERVEROperationCompleted(object arg) {
            if ((this.CONTACT_JAVA_SERVERCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CONTACT_JAVA_SERVERCompleted(this, new CONTACT_JAVA_SERVERCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class User {
        
        private int idField;
        
        private string user_NameField;
        
        private System.Nullable<int> model_IDField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string User_Name {
            get {
                return this.user_NameField;
            }
            set {
                this.user_NameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> Model_ID {
            get {
                return this.model_IDField;
            }
            set {
                this.model_IDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Image {
        
        private int idField;
        
        private string image_PathField;
        
        private System.Nullable<int> user_IDField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Image_Path {
            get {
                return this.image_PathField;
            }
            set {
                this.image_PathField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> User_ID {
            get {
                return this.user_IDField;
            }
            set {
                this.user_IDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void INSERT_IMAGECompletedEventHandler(object sender, INSERT_IMAGECompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class INSERT_IMAGECompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal INSERT_IMAGECompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void INSERT_USERCompletedEventHandler(object sender, INSERT_USERCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class INSERT_USERCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal INSERT_USERCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void UPDATE_TRAIN_DATACompletedEventHandler(object sender, UPDATE_TRAIN_DATACompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UPDATE_TRAIN_DATACompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UPDATE_TRAIN_DATACompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void TRAIN_IMAGES_MODELCompletedEventHandler(object sender, TRAIN_IMAGES_MODELCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TRAIN_IMAGES_MODELCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TRAIN_IMAGES_MODELCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void RETURN_TRAINED_MODELSCompletedEventHandler(object sender, RETURN_TRAINED_MODELSCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RETURN_TRAINED_MODELSCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RETURN_TRAINED_MODELSCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void RETURN_USERS_IN_MODELCompletedEventHandler(object sender, RETURN_USERS_IN_MODELCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RETURN_USERS_IN_MODELCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RETURN_USERS_IN_MODELCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void RETURN_USER_WITH_IDCompletedEventHandler(object sender, RETURN_USER_WITH_IDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RETURN_USER_WITH_IDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RETURN_USER_WITH_IDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void DECREMENT_IMAGES_MODEL_VERSIONCompletedEventHandler(object sender, DECREMENT_IMAGES_MODEL_VERSIONCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DECREMENT_IMAGES_MODEL_VERSIONCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DECREMENT_IMAGES_MODEL_VERSIONCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void return_UsersCompletedEventHandler(object sender, return_UsersCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class return_UsersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal return_UsersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public User[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((User[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void return_ImagesCompletedEventHandler(object sender, return_ImagesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class return_ImagesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal return_ImagesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Image[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Image[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void CONTACT_JAVA_SERVERCompletedEventHandler(object sender, CONTACT_JAVA_SERVERCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CONTACT_JAVA_SERVERCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CONTACT_JAVA_SERVERCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591