<?xml version="1.0" encoding="utf-8"?><Database Name="SSS_DATABASE_" Class="SSS_LINQ_DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.\SQLEXPRESS;Initial Catalog=SSS_DATABASE_;Integrated Security=True;Pooling=False" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="SSS_DATABASE_ConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Images" Member="Images">
    <Type Name="Image">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Image_Path" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="User_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Trained_Models" Member="Trained_Models">
    <Type Name="Trained_Model">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Model_Name" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Number_OF_Users" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Model_Version" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Trained_Models_Interaction_Data" Member="Trained_Models_Interaction_Datas">
    <Type Name="Trained_Models_Interaction_Data">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Model_Name" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Number_OF_Users" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Model_Version" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Trained_Models_Voice_Notes" Member="Trained_Models_Voice_Notes">
    <Type Name="Trained_Models_Voice_Note">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Model_Name" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Number_OF_Users" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Model_Version" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Voice_Notes" Member="Voice_Notes">
    <Type Name="Voice_Note">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Voice_Note_Path" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="User_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Users" Member="Users">
    <Type Name="User">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="User_Name" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Model_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Model_ID_VN" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Accuracy_Users" Member="Accuracy_Users">
    <Type Name="Accuracy_User">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="User_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Prediction_Accuracy_Images" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Validation_Accuracy_Images" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Prediction_Accuracy_VN" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Validation_Accuracy_VN" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Devices_Mac" Member="Devices_Macs">
    <Type Name="Devices_Mac">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Mac_Address" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="User_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
</Database>